name: warship_survival
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2
 
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flame:
  flutter_animation_progress_bar:   
  flare_flutter:  
  percent_indicator:  
  google_fonts:
  shared_preferences:    
  admob_flutter:
  auto_size_text:
  flutter_rating_bar:
  url_launcher:      
  
dev_dependencies:
  flutter_launcher_icons: 
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"


    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/audio/explosion.wav
    - assets/audio/life_pickup.flac
    - assets/audio/shooting.wav
    - assets/audio/shooting1.wav
    - assets/audio/background_music.wav
    - assets/audio/background_music1.wav
    - assets/images/player.png
    - assets/images/explosion.png
    - assets/images/stars.png
    - assets/images/bullet.png
    - assets/images/bullet1.png
    - assets/images/enemy.png
    - assets/images/player_ship_red.png
    - assets/images/joystick_knob.png
    - assets/images/joystick_background.png 
    - assets/images/atomic-bomb.png
    - assets/images/more.png
    - assets/images/laser.png
    - assets/images/spr_missile.png
    - assets/images/model1.png
    - assets/images/model2.png
    - assets/images/model3.png
    - assets/images/model4.png
    - assets/images/model5.png
    - assets/images/model6.png
    - assets/images/model7.png
    - assets/images/model8.png
    - assets/images/model9.png
    - assets/images/model10.png
    - assets/images/splash_bg.jpg
    - assets/images/vortex.png
    - assets/images/ic_launcher.png
    - assets/ammo.flr
    - assets/AmmoButton.flr
    - assets/Jupyter.flr
    - assets/Saturn.flr
    - assets/Planet.flr
    - assets/Gears.flr
    - assets/images/TxtMore.png
    - assets/images/TxtMulti.png
    - assets/images/TxtOptions.png
    - assets/images/TxtPlay.png
    - assets/images/TxtQuit.png
    - assets/images/TxtSingle.png
    - assets/images/TxtUpdate.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Karmatic
      fonts:
        - asset: fonts/ka1.ttf
    - family: Karma
      fonts:
        - asset: fonts/karma-future.ttf
    - family: ZeroVelo
      fonts:
        - asset: fonts/zerovelo.ttf       

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
